### PR TITLE
Fix the fixes

### PR DESCRIPTION
**Pull request by eerussianguy**
Removed some silliness on my part... Everything should be good now. The damage thing is broken on DT's end I am assuming, either way the current fix will have to do because I am not prying open that can of worms.

### CODE REVIEW

**Comment by eerussianguy** [comment]
Need to close #39 #37 #36 #29

**Comment by Gaelmare** [comment]
Looks good, thanks! Some remaining bugs before release. I think we need to fix #41 at least partially before we can release these.

**Comment by Gaelmare** [comment]
Wouldn't mind a fix for #42 as well.

**Comment by Gaelmare** [comment]
Result is still that some trees when chopped down give no logs at all.

**Pull request merged**
